sudo: false
language: python
python:
- '3.5'
install:
- pip install -r requirements-tests.txt --upgrade
- python setup.py install
script:
- py.test --muffin-app=example:app
env:
  global:
  - GH_REPO="ei-grad/muffin-classy"
