sudo: false
language: python
python:
- '3.5'
install:
- pip install -r requirements-tests.txt --upgrade
- python setup.py install
script:
- coverage run --include=muffin_classy.py `which py.test` --muffin-app=example:app
after_success:
- coveralls
env:
  global:
  - GH_REPO="ei-grad/muffin-classy"
